### ISSUE TITLE
Coin Album

### ISSUE THREAD

**Issue by Angelfc76** [skca91/cubo2dhub#44]
No existe boton de salida para cerrar la app, o para cambiar a otra app.

**Comment by Angelfc76** [comment]
El circulo indicador para capturar las imagenes es muy pequeño con relacion a la pantalla.
![WhatsApp Image 2022-10-05 at 12 08 29 PM](https://user-images.githubusercontent.com/115095836/194095824-86beebef-f9dd-4b91-b299-a8b892614bca.jpeg)

**Comment by Angelfc76** [comment]
> El circulo indicador para capturar las imagenes es muy pequeño con relacion a la pantalla. ![WhatsApp Image 2022-10-05 at 12 08 29 PM](https://user-images.githubusercontent.com/115095836/194095824-86beebef-f9dd-4b91-b299-a8b892614bca.jpeg)

**Comment by Angelfc76** [comment]
1. Boton de salida de la app, dejar habilitado el menu del cel en la aprte inferior.
2. En la pantalla de captura de imagenes se debe señalizar la función de los dos botones verdes que cambian la resolución y tamaño para capturar las fotos.
3. La paleta de colores se puede mejorar ese verde fuerte no queda bien para el tipo de app
4. Podemos cambiar el logo de la app por una moneda mas bonita.
5. Lo mas importante NO APAREZCO en la sección "nosotros"

**Comment by danielp299** [comment]
Tiene que hacer un issue por cada error

- [ ] Boton de salida de la app, dejar habilitado el menu del cel en la aprte inferior.

- [ ] En la pantalla de captura de imagenes se debe señalizar la función de los dos botones verdes que cambian la resolución y tamaño para capturar las fotos.

- [ ] La paleta de colores se puede mejorar ese verde fuerte no queda bien para el tipo de app.

- [ ] Podemos cambiar el logo de la app por una moneda mas bonita.

- [ ] Lo mas importante NO APAREZCO en la sección "nosotros"
